Feature calendar page
JoeyKraemer/Newspaper-1CT-1F pull request #47
Opened 2023-01-12 15:33 UTC by guntzel-sebastian

2023-01-13 08:50 UTC, JoeyKraemer requested changes

2023-01-13 08:50 UTC, JoeyKraemer commented on .env
> +#Specific project name
This file shouldnt be here, delete it

2023-01-13 08:50 UTC, JoeyKraemer commented on .idea/.gitignore
> +# Default ignored files
Are you using something out of the ".idea" folder if not please remove it

2023-01-13 08:50 UTC, JoeyKraemer commented on Calendar.php
> +        <div id="calendar">
Check indentation

2023-01-13 08:50 UTC, JoeyKraemer commented on Calendar.php
> +
remove empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on Calendar.php
> +
remove one empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on Calendar.php
> +
rm one empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on CalendarCSS.css
> +
rm empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on CalendarCSS.css
> +
rm empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on CalendarCSS.css
> +a{
space between "a" and "{" is missing, pleases look at the following as well

2023-01-13 08:50 UTC, JoeyKraemer commented on CalendarCSS.css
> +}
add empty line

2023-01-13 08:50 UTC, JoeyKraemer commented on CalendarCSS.css
> +}
add empty line at the end of the file

2023-01-13 08:50 UTC, JoeyKraemer commented on Calendar_demo.css
> +/*******************************Calendar Top Navigation*********************************/
is it necessary to be part of this git?  If not please remove the files

2023-01-13 08:50 UTC, JoeyKraemer commented on docker-compose.yaml
>          image: php:latest
rm this file, it should not be part of this branch

2023-01-13 08:50 UTC, JoeyKraemer commented on calendarPHPBack.php
> +    // <div id="date"><span style="font-size: 3em;" id="calendarDate">10</span><h3>January <br> 2023</h3></div>
rm commented code

2023-01-13 11:31 UTC, YohanLoz requested changes
okay, the calendar desperately needs to be able to switch months (i.e. look at februari when it's currently january). 
the comments need to be reworked (For multiple lines of code use <!-- all code --> and only use // for single lines or comments). 
more comments are also required for things like "for ($d=1;$d<=$lastDay;$d++) {" because i have no idea what this does and especially not what it's for. 
also use 1 multi-line echo for large pieces of html instead of 10 seperate echo statements. Another thing is that the calendar should not have events where active = 0, (this should be easy to do, even with the current time constraints). 
max participants also seems to be absent from the data (this one is not that neccesary). 
whelp, good luck with all this.

2023-01-13 22:32 UTC, guntzel-sebastian commented
Feedback has been implemented, only remaining issue is the User name function that would come from the login system.

2023-01-14 15:15 UTC, JoeyKraemer submitted a review, later dismissed

2023-01-14 15:21 UTC, JoeyKraemer approved these changes

2023-01-14 15:22 UTC, merged